In [1]:
import numpy as np

# 1

In [2]:
A = np.array([[1,0,2],
              [0,1,1],
              [1,2,2]])
A

array([[1, 0, 2],
       [0, 1, 1],
       [1, 2, 2]])

In [3]:
E = np.identity(3)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
#AB = 2B - A
#(A-2E)B = -A

# B = (A-2E)^-1 * (-A)
A_minus_2_inverse = np.linalg.inv(A - 2*E)
minus_A = -A

In [5]:
B = np.dot(A_minus_2_inverse, minus_A)

In [6]:
print(B)

[[ 0.  -2.  -1. ]
 [-0.5  0.  -0.5]
 [-0.5 -1.  -1.5]]


# 2

## 2-1

In [7]:
matrix_a = np.array([[2,-1,-3],
                     [-1,-2,-3],
                     [1,1,4],])
matrix_a_inverse = np.linalg.inv(matrix_a)
matrix_b = np.array([[2],
                   [-1],
                   [1]])

In [8]:
x = np.dot(matrix_a_inverse, matrix_b)
print(x)

[[1.]
 [0.]
 [0.]]


## 2-2

In [9]:
try:
    matrix_c = np.array([[2,-1,-3],
                         [-4,2,6],
                         [3,1,4],])
    matrix_c_inverse = np.linalg.inv(matrix_c)
    matrix_d = np.array([[2],
                       [-1],
                       [1]])
    #det(c) = 2(8-6) -(-1)(-16-18) +(-3)(-4-6) = 4 -34 + 30 = 0
except:
    print("det의 값이 0인 특이행렬은 역행렬이 존재하지 않습니다.")

det의 값이 0인 특이행렬은 역행렬이 존재하지 않습니다.


# 3

In [10]:
def f(array):
    return np.array([value for row_matrix in array for value in row_matrix])

In [11]:
f(np.array([[1,2],[2,3]]))

array([1, 2, 2, 3])

In [12]:
f(np.array([[1,2,3],[2,3,4],[3,4,5]]))

array([1, 2, 3, 2, 3, 4, 3, 4, 5])

# 4

In [13]:
#행 기준 : 받는게 누구인지?
#열 기준 : 주는게 누구인지?
x = np.array([[0.6, 0.3],
               [0.4, 0.7]])
x0 = np.array([[0, 1.0]]).T

In [14]:
#1개월 후
x1 = x.dot(x0)
x1

array([[0.3],
       [0.7]])

In [15]:
#2개월 후
x2 = x.dot(x1)
x2

array([[0.39],
       [0.61]])

In [16]:
print(x2)

[[0.39]
 [0.61]]


# 5

In [17]:
def x(t):
    x = np.array([[0.6, 0.3],
                   [0.4, 0.7]])
    x0 = np.array([[1, 0]]).T
    for i in range (t):
        x0 = x.dot(x0)
    return x0

In [18]:
x(10)

array([[0.4285748],
       [0.5714252]])